### PR TITLE
Fix soccer height

### LINKED ISSUE #21: Soccer Dataset: The 0 height values should be changed to Missing values.
Soccer Dataset: The 0 height values should be changed to Missing values.

### PR DESCRIPTION
**Pull request by thinkh**
closes #21 

**prerequisites**: 
 * [x] branch is up-to-date with the branch to be merged with, i.e. develop
 * [x] build is successful
 * [x] code is cleaned up and formatted 

### Summary
Removed the height value for players with height = 0.

image

As shown in the screenshot LineUp renders the missing values itself correct, but the text on hover shows `null`. It would be nice, if text would be empty (as it is for other column types).

### CODE REVIEW

File: src/data/soccer/index.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ export const data: IDataset = {
     .column(buildStringColumn('current_club'))
     .column(buildCategoricalColumn('current_league'))
     .column(buildCategoricalColumn('foot'))
-    .column(buildNumberColumn('height', [0, NaN]))
+    .column(buildNumberColumn('height', [NaN, NaN]))
```
Comment (sgratzl) [inline src/data/soccer/index.ts]: why did you change to derived minimum? I mean 0 is the minimal height of a person?

Comment (thinkh) [reply src/data/soccer/index.ts]: Because the histogram is more meaningful, since there is no person with 0. But if you want you can change it back.
